import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { store } from "@/store/store";
import { StoreProvider } from "@/StoreProvider";
import { CountProvider } from "@/CountProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>{children}</StoreProvider>
        {/* <CountProvider>{children}</CountProvider> */}
      </body>
    </html>
  );
}
